version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: ordermatching-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT_INTERNAL}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  mysql_data: