version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: ordermatching-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${MYSQL_PORT_EXTERNAL}:${MYSQL_PORT_INTERNAL}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordermatching-app
    restart: unless-stopped
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_PORT_EXTERNAL: ${MYSQL_PORT_EXTERNAL}
      PORT: ${APP_PORT}
    depends_on:
      - mysql
    command: ["./main"]

volumes:
  mysql_data: